spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123
  redis:
    host: 192.168.10.130
    port: 6379

server:
  port: 8080

#mybatis-plus:
#  mapper-locations: "classpath*:/mapper/**/*.xml"